// eslint-disable-next-line import/no-anonymous-default-export
export default {
  container: {
    display: 'flex',
    flexDirection: 'column',
    cursor: 'context-menu',
  },
  curveBackground: {
    flexDirection: 'row',
    backgroundImage: 'linear-gradient(to right, #82a2c4, #326ba8)',
    height: 100,
    borderBottomLeftRadius: '75%',
    borderBottomRightRadius: '75%',
    boxShadow: '-4px 4px 5px -3px rgba(0,0,0,0.425)',
    position: 'fixed',
    width: '100vw',
  },
  inputBox: {
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: '#ccc',
    height: 34,
    paddingLeft: 10,
    boxShadow: '2px 2px 8px -2px rgba(0,0,0,0.425)',
    backgroundColor: '#ededed',
    outlineWidth: 0,
    color: '#8c8989',
    fontFamily: 'cursive',
    cursor: 'context-menu',
    fontSize: 16,
  },
  neumorphism: {
    height: 80,
    width: 80,
    borderRadius: 50,
    backgroundColor: 'rgb(219,218,218)',
    boxShadow:
      '-2px -3px 5px -3px rgba(255, 255, 255, 0.425), 2px 3px 5px -3px rgba(88, 88, 88, 0.425)',
  },
  spinningLoader: {
    height: 50,
    width: 50,
    border: '4px solid white',
    borderRadius: '50%',
    borderTop: '4px solid pink',
    borderBottom: '4px solid pink',
  },
  btn: {
    backgroundColor: '#82a2c4',
    color: '#fff',
    fontWeight: 'bold',
    transition: '0.25s',
    boxShadow: '2px 2px 8px -2px rgba(0,0,0,0.425)',
    borderRadius: '25% 50%',
    cursor: 'pointer',
    marginLeft: 10,
    padding: 8,
  },
  length: {
    height: 10,
    borderRadius: 100,
    backgroundColor: 'red',
    color: 'white',
    transition: '5s linear',
  },
  taskCard: {
    margin: 10,
    padding: '5px 20px 5px 20px',
    boxShadow: '1px 1px 5px -2px rgba(0,0,0,0.25)',
    borderRadius: 4,
    // height: 'auto',
    // transition: 'height 0.1s linear',
    color: '#8c8989',
    fontFamily: 'cursive',
    backgroundColor: 'white',
    width: '60%',
  },
  myPlansText: {
    alignSelf: 'center',
    textAlign: 'center',
    marginTop: 120,
    position: 'fixed',
    width: '100vw',
    fontFamily: 'cursive',
    color: '#d68d8d',
    textDecoration: 'underline',
    fontSize: 18,
  },
};
